### PR TITLE
Run screenshotting in subprocesses

### PR DESCRIPTION
**Pull request by jwodder**
Closes https://github.com/dandi/dandi-api-webshots/issues/19.

### CODE REVIEW

**Review by yarikoptic — COMMENTED** [review]
one minor comment, but primary question: did you try running it and see that result of the execution brings no differences to the snapshots?  
I have tried on staging and it seems that all */edit-metadata.png are gone, and landing are changed.

**Comment by jwodder** [comment]
@yarikoptic edit-metadata fixed.  What do you mean by "landing are changed"?

**Comment by yarikoptic** [comment]
> @yarikoptic edit-metadata fixed. What do you mean by "landing are changed"?

There was a diff to landing.png for dandisets on staging, although I would've expected them to be the same

**Comment by jwodder** [comment]
@yarikoptic Do the images actually look different, or is it just a binary difference?  Perhaps something on staging changed.

**Comment by yarikoptic** [comment]
> @yarikoptic Do the images actually look different, or is it just a binary difference? Perhaps something on staging changed.

please make a run on a few dandisets on master branch and then this one, and compare images if anything changes.

<details>
<summary>FWIW here is the `imgdiff` I use</summary> 

```
#!/bin/bash

set -u
out=`mktemp --dry-run`.png
#trap "rm -rf $out" 0

mode=${IMGDIFF_MODE:-lum}
echo "Invoked with $@ . out=$out" >> /tmp/log
ls -ld "$@" >> /tmp/log
#shift
# recipes from https://stackoverflow.com/questions/5132749/diff-an-image-using-imagemagick

case $mode in
# to make it RG difference on top of common grayscale
lum)
	convert '(' "$1" -flatten -grayscale Rec709Luminance ')' \
			'(' "$2" -flatten -grayscale Rec709Luminance ')' \
			'(' -clone 0-1 -compose darken -composite ')' \
			-channel RGB -combine $out;;
# darker $1 with blue diff on top
bluediff)
	compare \
			"$1" "$2" \
		   -highlight-color blue \
			$out;;
compose)
    compare -compose src "$1" "$2" "$out";;
esac

display $out
#rm -f $out
```

</details>

and I have
```
$> git config --list | grep imgdiff
alias.imgdiff=difftool -x imgdiff --no-prompt
difftool.imgdiff.cmd=imgdiff
```

**Comment by jwodder** [comment]
@yarikoptic I ran the script on Dandisets 000003 through 000009 on staging, and the only differences were that, for Dandisets other than 000003, the "Edit Metadata" button in the landing snapshot was highlighted when snapshotted with the master code but not with the branch code; also, for 000006/view-data, the master code had one of the folders highlighted.

**Comment by yarikoptic** [comment]
tested too -- no differences now. Thank you! Let's proceed

**Pull request merged**
